#! /bin/sh

### BEGIN INIT INFO
# Provides:          mongodb
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the mongodb data-store
# Description:       starts mongodb using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

DAEMON=/opt/mongodb/bin/mongod
PIDFILE=/var/run/mongodb.pid
CONF="/etc/mongodb/mongodb.conf"
NAME=mongodb
DESC=mongodb

test -x $DAEMON || exit 0

#set -e

$DAEMON --config $CONF --repair


case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --pidfile $PIDFILE --exec $DAEMON --start -- run --config $CONF --fork --pidfilepath $PIDFILE 
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --quiet --pidfile $PIDFILE --stop --exec $DAEMON -- --config $CONF --shutdown 
        echo "$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --quiet --pidfile $PIDFILE --config $CONF --exec $DAEMON --stop
        sleep 1
        start-stop-daemon --quiet --pidfile $PIDFILE --exec $DAEMON --start -- run --config $CONF
        echo "$NAME."
        ;;
  reload)
      echo -n "Reloading $DESC configuration: "
      start-stop-daemon --stop --signal HUP --quiet --config $CONF --pidfile $PIDFILE --exec $DAEMON
      echo "$NAME."
      ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0

