package ch.fork.AdHocRailway.domain.turnouts;

// Generated 08-Aug-2007 18:10:44 by Hibernate Tools 3.2.0.beta8

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TurnoutAddress generated by hbm2java
 */
@Entity
@Table(name = "turnout_address", catalog = "adhocrailway", uniqueConstraints = {})
public class TurnoutAddress implements java.io.Serializable {

	// Fields    

	private int id;

	private Turnout turnout;

	private int address;

	private int bus;

	private boolean switched;

	// Constructors

	/** default constructor */
	public TurnoutAddress() {
	}

	/** full constructor */
	public TurnoutAddress(int id, Turnout turnout, int address, int bus,
			boolean switched) {
		this.id = id;
		this.turnout = turnout;
		this.address = address;
		this.bus = bus;
		this.switched = switched;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "turnout_id", unique = false, nullable = false, insertable = true, updatable = true)
	public Turnout getTurnout() {
		return this.turnout;
	}

	public void setTurnout(Turnout turnout) {
		this.turnout = turnout;
	}

	@Column(name = "address", unique = false, nullable = false, insertable = true, updatable = true)
	public int getAddress() {
		return this.address;
	}

	public void setAddress(int address) {
		this.address = address;
	}

	@Column(name = "bus", unique = false, nullable = false, insertable = true, updatable = true)
	public int getBus() {
		return this.bus;
	}

	public void setBus(int bus) {
		this.bus = bus;
	}

	@Column(name = "switched", unique = false, nullable = false, insertable = true, updatable = true)
	public boolean isSwitched() {
		return this.switched;
	}

	public void setSwitched(boolean switched) {
		this.switched = switched;
	}

}
