package ch.fork.AdHocRailway.domain.turnouts;

// Generated 08-Aug-2007 18:10:44 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import ch.fork.AdHocRailway.domain.ControlObject;
import ch.fork.AdHocRailway.domain.routes.RouteItem;
import ch.fork.AdHocRailway.domain.turnouts.TurnoutType.TurnoutTypes;
import de.dermoba.srcp.client.SRCPSession;
import de.dermoba.srcp.devices.GA;

/**
 * Turnout generated by hbm2java
 */
@Entity
@Table(name = "turnout", catalog = "adhocrailway", uniqueConstraints = { @UniqueConstraint(columnNames = { "number" }) })
public class Turnout extends ControlObject implements java.io.Serializable,
		Comparable<Turnout> {

	// Fields

	@Id @GeneratedValue
	private int id;

	private TurnoutType turnoutType;

	private TurnoutGroup turnoutGroup;

	private int number;

	private String description;

	private String defaultState;

	private String orientation;

	private Set<RouteItem> routeItems = new HashSet<RouteItem>(0);

	private int address1;

	private int address2;

	private int bus1;

	private int bus2;

	private boolean address1_switched;

	private boolean address2_switched;

	public enum TurnoutState {
		LEFT, STRAIGHT, RIGHT, UNDEF
	}

	public enum TurnoutOrientation {
		NORTH, SOUTH, WEST, EAST
	};

	@Transient
	protected TurnoutState turnoutState = TurnoutState.UNDEF;

	public static final String PROTOCOL = "M";

	private Turnout[] subTurnouts;
	private GA ga;

	private SRCPSession session;

	@Transient
	public GA getGA() {
		return this.ga;
	}

	@Transient
	protected void setGA(GA ga) {
		this.ga = ga;
	}

	@Transient
	public SRCPSession getSession() {
		return this.session;
	}

	@Transient
	protected void setSession(SRCPSession session) {
		this.session = session;
	}

	@Override
	@Transient
	public String getDeviceGroup() {
		return "GA";
	}

	@Transient
	public TurnoutState getTurnoutState() {
		return turnoutState;
	}

	@Transient
	protected void setTurnoutState(TurnoutState switchState) {
		this.turnoutState = switchState;
	}

	@Transient
	public TurnoutState getDefaultStateEnum() {
		if (defaultState.toUpperCase().equals("STRAIGHT")) {
			return TurnoutState.STRAIGHT;
		} else if (defaultState.toUpperCase().equals("LEFT")) {
			return TurnoutState.LEFT;
		} else if (defaultState.toUpperCase().equals("RIGHT")) {
			return TurnoutState.RIGHT;
		}
		return TurnoutState.UNDEF;
	}

	public void setDefaultStateEnum(TurnoutState state) {
		switch (state) {
		case STRAIGHT:
			setDefaultState("STRAIGHT");
			break;
		case LEFT:
			setDefaultState("LEFT");
			break;
		case RIGHT:
			setDefaultState("RIGHT");
			break;
		default:
			setDefaultState("UNDEF");
		}
	}

	public void setOrientationEnum(TurnoutOrientation orientation) {
		switch (orientation) {
		case NORTH:
			setOrientation("NORTH");
			break;
		case SOUTH:
			setOrientation("SOUTH");
			break;
		case WEST:
			setOrientation("WEST");
			break;
		case EAST:
			setOrientation("EAST");
			break;
		}
	}

	@Override
	@Transient
	public int[] getAddresses() {
		int[] addrs = new int[] { address1, address2 };
		return addrs;
	}

	@Transient
	public TurnoutAddress[] getTurnoutAddresses() {
		return new TurnoutAddress[] {
				new TurnoutAddress(address1, bus1, address1_switched),
				new TurnoutAddress(address2, bus2, address2_switched) };
	}

	@Transient
	public TurnoutAddress getTurnoutAddress(int index) {
		return getTurnoutAddresses()[index];
	}

	@Transient
	public boolean isDefault() {
		return this.turnoutType.getTurnoutTypeEnum() == TurnoutTypes.DEFAULT;
	}

	@Transient
	public boolean isDoubleCross() {
		return this.turnoutType.getTurnoutTypeEnum() == TurnoutTypes.DOUBLECROSS;
	}

	@Transient
	public boolean isThreeWay() {
		return this.turnoutType.getTurnoutTypeEnum() == TurnoutTypes.THREEWAY;
	}

	@Transient
	public TurnoutOrientation getOrientationEnum() {
		if (orientation.toUpperCase().equals("NORTH")) {
			return TurnoutOrientation.NORTH;
		} else if (orientation.toUpperCase().equals("SOUTH")) {
			return TurnoutOrientation.SOUTH;
		} else if (orientation.toUpperCase().equals("EAST")) {
			return TurnoutOrientation.EAST;
		} else if (orientation.toUpperCase().equals("WEST")) {
			return TurnoutOrientation.WEST;
		}
		return null;
	}

	@Transient
	protected Turnout[] getSubTurnouts() {
		return subTurnouts;
	}

	@Transient
	protected void setSubTurnouts(Turnout[] subTurnouts) {
		this.subTurnouts = subTurnouts;
	}


	public int compareTo(Turnout o) {
		if (this == o)
			return 0;
		if (o == null)
			return -1;
		if (number > o.getNumber())
			return 1;
		else if (number == o.getNumber())
			return 0;
		else
			return -1;
	}

	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;

		Turnout t = (Turnout) o;

		if (number != t.getNumber())
			return false;
		if (id != t.getId())
			return false;
		if (!turnoutGroup.equals(t.getTurnoutGroup()))
			return false;
		if (!turnoutType.equals(t.getTurnoutType()))
			return false;
		if (!description.equals(t.getDescription()))
			return false;
		if (!defaultState.equals(t.getDefaultState()))
			return false;
		if (!orientation.equals(t.getOrientation()))
			return false;
		if (address1 != t.getAddress1())
			return false;
		if (address2 != t.getAddress2())
			return false;
		return true;
	}

	public int hashCode() {
		return id + number + address1 + address2 + bus1 + bus2;
	}

	public String toString() {

		String buf = "\"" + number + ": " + getTurnoutType().getTypeName()
				+ " @";

		buf += " " + getTurnoutAddress(0);
		if (turnoutType.getTypeName().equals("ThreeWay"))
			buf += " " + getTurnoutAddress(1);
		buf += " Group:" + turnoutGroup.toString();
		return buf;
	}
	
	// GENERATED BY HIBERNATE
	// Constructors

	/** default constructor */
	public Turnout() {
	}

	/** minimal constructor */
	public Turnout(int id, TurnoutType turnoutType, TurnoutGroup turnoutGroup,
			int number, String description, String defaultState,
			String orientation, int address1, int bus1,
			boolean address1_switched) {
		this.id = id;
		this.turnoutType = turnoutType;
		this.turnoutGroup = turnoutGroup;
		this.number = number;
		this.description = description;
		this.defaultState = defaultState;
		this.orientation = orientation;
		this.address1 = address1;
		this.bus1 = bus1;
		this.address1_switched = address1_switched;
	}

	/** full constructor */
	public Turnout(int id, TurnoutType turnoutType, TurnoutGroup turnoutGroup,
			int number, String description, String defaultState,
			String orientation, Set<RouteItem> routeItems, int address1,
			int address2, int bus1, int bus2, boolean address1_switched,
			boolean address2_switched) {
		this.id = id;
		this.turnoutType = turnoutType;
		this.turnoutGroup = turnoutGroup;
		this.number = number;
		this.description = description;
		this.defaultState = defaultState;
		this.orientation = orientation;
		this.routeItems = routeItems;
		this.address1 = address1;
		this.address2 = address2;
		this.bus1 = bus1;
		this.bus2 = bus2;
		this.address1_switched = address1_switched;
		this.address2_switched = address2_switched;

	}

	// Property accessors
	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	@JoinColumn(name = "turnout_type_id", unique = false, nullable = false, insertable = true, updatable = true)
	public TurnoutType getTurnoutType() {
		return this.turnoutType;
	}

	public void setTurnoutType(TurnoutType turnoutType) {
		this.turnoutType = turnoutType;
	}

	@ManyToOne(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	@JoinColumn(name = "turnout_group_id", unique = false, nullable = false, insertable = true, updatable = true)
	public TurnoutGroup getTurnoutGroup() {
		return this.turnoutGroup;
	}

	public void setTurnoutGroup(TurnoutGroup turnoutGroup) {
		this.turnoutGroup = turnoutGroup;
	}

	@Column(name = "number", unique = true, nullable = false, insertable = true, updatable = true)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Column(name = "description", unique = false, nullable = true, insertable = true, updatable = true)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "default_state", unique = false, nullable = false, insertable = true, updatable = true, length = 9)
	public String getDefaultState() {
		return this.defaultState;
	}

	public void setDefaultState(String defaultState) {
		this.defaultState = defaultState;
	}

	@Column(name = "orientation", unique = false, nullable = false, insertable = true, updatable = true, length = 6)
	public String getOrientation() {
		return this.orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "turnout")
	public Set<RouteItem> getRouteItems() {
		return this.routeItems;
	}

	public void setRouteItems(Set<RouteItem> routeItems) {
		this.routeItems = routeItems;
	}

	@Column(name = "address1", unique = false, nullable = false, insertable = true, updatable = true)
	public int getAddress1() {
		return this.address1;
	}

	public void setAddress1(int address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", unique = false, nullable = true, insertable = true, updatable = true)
	public int getAddress2() {
		return this.address2;
	}

	public void setAddress2(int address2) {
		this.address2 = address2;
	}

	@Column(name = "bus1", unique = false, nullable = false, insertable = true, updatable = true)
	public int getBus1() {
		return this.bus1;
	}

	public void setBus1(int bus1) {
		this.bus1 = bus1;
	}

	@Column(name = "bus2", unique = false, nullable = true, insertable = true, updatable = true)
	public int getBus2() {
		return this.bus2;
	}

	public void setBus2(int bus2) {
		this.bus2 = bus2;
	}

	@Column(name = "address1_switched", unique = false, nullable = false, insertable = true, updatable = true)
	public boolean isAddress1Switched() {
		return this.address1_switched;
	}

	public void setAddress1Switched(boolean address1_switched) {
		this.address1_switched = address1_switched;
	}

	@Column(name = "address2_switched", unique = false, nullable = true, insertable = true, updatable = true)
	public boolean isAddress2Switched() {
		return this.address2_switched;
	}

	public void setAddress2Switched(boolean address2_switched) {
		this.address2_switched = address2_switched;
	}
}
