package ch.fork.AdHocRailway.domain.turnouts;

// Generated 08-Aug-2007 18:10:44 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TurnoutGroup generated by hbm2java
 */
@Entity
@Table(name = "turnout_group", catalog = "adhocrailway", uniqueConstraints = {})
public class TurnoutGroup implements java.io.Serializable {

	// Fields    

	private int id;

	private String name;

	private Set<Turnout> turnouts = new HashSet<Turnout>(0);

	// Constructors

	/** default constructor */
	public TurnoutGroup() {
	}

	/** minimal constructor */
	public TurnoutGroup(int id, String name) {
		this.id = id;
		this.name = name;
	}

	/** full constructor */
	public TurnoutGroup(int id, String name, Set<Turnout> turnouts) {
		this.id = id;
		this.name = name;
		this.turnouts = turnouts;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "turnoutGroup")
	public Set<Turnout> getTurnouts() {
		return this.turnouts;
	}

	public void setTurnouts(Set<Turnout> turnouts) {
		this.turnouts = turnouts;
	}

}
