package ch.fork.AdHocRailway.domain.turnouts;

// Generated 08-Aug-2007 18:10:44 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TurnoutType generated by hbm2java
 */
@Entity
@Table(name = "turnout_type", catalog = "adhocrailway", uniqueConstraints = {})
public class TurnoutType implements java.io.Serializable {

	// Fields    

	private int id;

	private String typeName;

	private Set<Turnout> turnouts = new HashSet<Turnout>(0);

	// Constructors

	/** default constructor */
	public TurnoutType() {
	}

	/** minimal constructor */
	public TurnoutType(int id, String typeName) {
		this.id = id;
		this.typeName = typeName;
	}

	/** full constructor */
	public TurnoutType(int id, String typeName, Set<Turnout> turnouts) {
		this.id = id;
		this.typeName = typeName;
		this.turnouts = turnouts;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type_name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "turnoutType")
	public Set<Turnout> getTurnouts() {
		return this.turnouts;
	}

	public void setTurnouts(Set<Turnout> turnouts) {
		this.turnouts = turnouts;
	}

}
