#-------------------------------------------------------------------------
#
# <java.mk>  -  <desc>
#
# begin     : Mon Apr 25 22:20:52 CEST 2005
# copyright : (C)  by Benjamin Mueller 
# email     : akula@akula.ch
# language  : make
# version   : $Id$
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
#-------------------------------------------------------------------------

JIKES=/usr/bin/jikes
EXTRALIBS=
CP=/usr/lib/sun-j2sdk1.5.0/jre/lib/rt.jar:/usr/share/java/junit.jar:/usr/share/java/emma.jar:/usr/share/java/emma_ant.jar:$(EXTRALIBS):./src:./classes
JIKES_FLAGS=-classpath $(CP) -Xstdout +E -d ./classes
JAVAC=/usr/bin/javac
JAVA_FLAGS=-classpath $(CP)
JAVA=/usr/bin/java
EMMA_FLAGS=emmarun -r html -cp $(CP) -sp ./src
EMMA=$(JAVA) $(JAVA_FLAGS) $(EMMA_FLAGS)
JAVA_SOURCES=$(shell find ./src -name "*.java")

OBJS=$(addsuffix .class, $(basename $(JAVA_SOURCES)))

# Importing build-dependencies generated by jikes
DEPENDENCIES=$(addsuffix .u, $(basename $(JAVA_SOURCES)))

CLEAN_LIST+=$(foreach f,$(shell find ./src -name "*.class"), '$f')
CLEAN_LIST+=$(foreach f,$(shell find ./src -name "*.u"), '$f')

.PHONY: clean
build: $(DEPENDENCIES) $(OBJS)

include $(DEPENDENCIES)
	
%.class: %.java
	$(JIKES) $(JIKES_FLAGS) $<

%.u: %.java
	$(JIKES) $(JIKES_FLAGS) --makefile --nobytecode $<

clean ::
	$(if $(CLEAN_LIST),rm -rf $(CLEAN_LIST))

test: src/RailControlGUI.class
	$(JAVA) $(JAVA_FLAGS) RailControlGUI

# " vim:ts=4
