package ch.fork.AdHocRailway.domain.routes;

// Generated 08-Aug-2007 18:10:44 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RouteGroup generated by hbm2java
 */
@Entity
@Table(name = "route_group", catalog = "adhocrailway", uniqueConstraints = {})
public class RouteGroup implements java.io.Serializable {

	// Fields    

	private int id;

	private String name;

	private Set<Route> routes = new HashSet<Route>(0);

	// Constructors

	/** default constructor */
	public RouteGroup() {
	}

	/** minimal constructor */
	public RouteGroup(int id, String name) {
		this.id = id;
		this.name = name;
	}

	/** full constructor */
	public RouteGroup(int id, String name, Set<Route> routes) {
		this.id = id;
		this.name = name;
		this.routes = routes;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "routeGroup")
	public Set<Route> getRoutes() {
		return this.routes;
	}

	public void setRoutes(Set<Route> routes) {
		this.routes = routes;
	}

}
