package ch.fork.AdHocRailway.domain.routes;

// Generated 08-Aug-2007 18:10:44 by Hibernate Tools 3.2.0.beta8

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ch.fork.AdHocRailway.domain.turnouts.Turnout;

/**
 * RouteItem generated by hbm2java
 */
@Entity
@Table(name = "route_item", catalog = "adhocrailway", uniqueConstraints = {})
public class RouteItem implements java.io.Serializable {

	// Fields    

	private int id;

	private Turnout turnout;

	private Route route;

	private String routedState;

	// Constructors

	/** default constructor */
	public RouteItem() {
	}

	/** full constructor */
	public RouteItem(int id, Turnout turnout, Route route, String routedState) {
		this.id = id;
		this.turnout = turnout;
		this.route = route;
		this.routedState = routedState;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "turnout_id", unique = false, nullable = false, insertable = true, updatable = true)
	public Turnout getTurnout() {
		return this.turnout;
	}

	public void setTurnout(Turnout turnout) {
		this.turnout = turnout;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "route_id", unique = false, nullable = false, insertable = true, updatable = true)
	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	@Column(name = "routed_state", unique = false, nullable = false, insertable = true, updatable = true, length = 9)
	public String getRoutedState() {
		return this.routedState;
	}

	public void setRoutedState(String routedState) {
		this.routedState = routedState;
	}

}
