/*------------------------------------------------------------------------
 * 
 * copyright : (C) 2008 by Benjamin Mueller 
 * email     : news@fork.ch
 * website   : http://sourceforge.net/projects/adhocrailway
 * version   : $Id$
 * 
 *----------------------------------------------------------------------*/

/*------------------------------------------------------------------------
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 *----------------------------------------------------------------------*/

package ch.fork.AdHocRailway.domain.routes;

// Generated 08-Aug-2007 18:10:44 by Hibernate Tools 3.2.0.beta8

import java.util.SortedSet;
import java.util.TreeSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Sort;
import org.hibernate.annotations.SortType;

import com.jgoodies.binding.beans.Model;

/**
 * RouteGroup generated by hbm2java
 */
@Entity
@Table(name = "route_group", catalog = "adhocrailway", uniqueConstraints = {})
public class RouteGroup extends Model implements java.io.Serializable,
		Comparable<RouteGroup> {

	// Fields

	@Id
	@GeneratedValue
	private int					id;

	private String				name;
	private int					routeNumberOffset;

	private int					routeNumberAmount;

	@Sort(type = SortType.NATURAL)
	private SortedSet<Route>	routes								= new TreeSet<Route>();

	public static final String	PROPERTYNAME_ID						= "id";
	public static final String	PROPERTYNAME_NAME					= "name";
	public static final String	PROPERTYNAME_ROUTE_NUMBER_OFFSET	= "routeNumberOffset";
	public static final String	PROPERTYNAME_ROUTE_NUMBER_AMOUNT	= "routeNumberAmount";
	public static final String	PROPERTYNAME_ROUTES					= "routes";

	public int compareTo(RouteGroup o) {
		if (this == o)
			return 0;
		if (o == null)
			return -1;
		// if(weight > o.getWeight()) return 1;
		// if(weight == o.getWeight()) return 0;
		// if(weight < o.getWeight()) return -1;
		// return -1;
		return name.compareTo(o.getName());
	}

	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;

		final RouteGroup l = (RouteGroup) o;
		if (id != l.getId())
			return false;
		if (!name.equals(l.getName()))
			return false;
		return true;
	}

	public int hashCode() {
		return name.hashCode();
	}

	public String toString() {
		return name;
	}

	// Constructors

	/** default constructor */
	public RouteGroup() {
	}

	/** minimal constructor */
	public RouteGroup(int id, String name, int routeNumberOffset,
			int routeNumberAmount) {
		this.id = id;
		this.name = name;
		this.routeNumberOffset = routeNumberOffset;
		this.routeNumberAmount = routeNumberAmount;
	}

	/** full constructor */
	public RouteGroup(int id, String name, int routeNumberOffset,
			int routeNumberAmount, SortedSet<Route> routes) {
		this.id = id;
		this.name = name;
		this.routeNumberOffset = routeNumberOffset;
		this.routeNumberAmount = routeNumberAmount;
		this.routes = routes;
	}

	// Property accessors

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		int old = id;
		this.id = id;
		firePropertyChange(PROPERTYNAME_ID, old, id);
	}

	@Column(name = "name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getName() {
		return this.name;
	}

	@Column(name = "route_number_offset", unique = false, nullable = false, insertable = true, updatable = true)
	public int getRouteNumberOffset() {
		return this.routeNumberOffset;
	}

	public void setRouteNumberOffset(int turnoutNumberOffset) {
		int old = this.routeNumberOffset;
		this.routeNumberOffset = turnoutNumberOffset;
		firePropertyChange(PROPERTYNAME_ID, old, turnoutNumberOffset);
	}

	@Column(name = "route_number_amount", unique = false, nullable = false, insertable = true, updatable = true)
	public int getRouteNumberAmount() {
		return this.routeNumberAmount;
	}

	public void setRouteNumberAmount(int turnoutNumberAmount) {
		int old = this.routeNumberAmount;
		this.routeNumberAmount = turnoutNumberAmount;
		firePropertyChange(PROPERTYNAME_ID, old, turnoutNumberAmount);
	}

	public void setName(String name) {
		String old = this.name;
		this.name = name;
		firePropertyChange(PROPERTYNAME_NAME, old, name);
	}

	@Sort(type = SortType.NATURAL)
	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "routeGroup")
	public SortedSet<Route> getRoutes() {
		return this.routes;
	}

	@Sort(type = SortType.NATURAL)
	public void setRoutes(SortedSet<Route> routes) {
		SortedSet<Route> old = routes;
		this.routes = routes;
		firePropertyChange(PROPERTYNAME_ROUTES, old, routes);
	}
}
