/*------------------------------------------------------------------------
 * 
 * copyright : (C) 2008 by Benjamin Mueller 
 * email     : news@fork.ch
 * website   : http://sourceforge.net/projects/adhocrailway
 * version   : $Id$
 * 
 *----------------------------------------------------------------------*/

/*------------------------------------------------------------------------
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 *----------------------------------------------------------------------*/

package ch.fork.AdHocRailway.domain.locomotives;

// Generated 08-Aug-2007 18:10:44 by Hibernate Tools 3.2.0.beta8

import java.util.SortedSet;
import java.util.TreeSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Sort;
import org.hibernate.annotations.SortType;

import com.jgoodies.binding.beans.Model;

/**
 * LocomotiveGroup generated by hbm2java
 */
@Entity
@Table(name = "locomotive_group", uniqueConstraints = {})
public class LocomotiveGroup extends Model implements java.io.Serializable,
		Comparable<LocomotiveGroup> {

	// Fields

	@Id
	@GeneratedValue
	private int						id;

	private String					name;

	@Sort(type = SortType.NATURAL)
	private SortedSet<Locomotive>	locomotives					= new TreeSet<Locomotive>();

	private static final String		PROPERTYNAME_ID				= "id";
	private static final String		PROPERTYNAME_NAME			= "name";
	private static final String		PROPERTYNAME_LOCOMOTIVES	= "locomotives";

	public int compareTo(LocomotiveGroup o) {
		if (this == o)
			return 0;
		if (o == null)
			return -1;
		return name.compareTo(o.getName());
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final LocomotiveGroup other = (LocomotiveGroup) obj;
		if (id != other.id)
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	public String toString() {
		return name;
	}

	// Constructors

	/** default constructor */
	public LocomotiveGroup() {
	}

	/** minimal constructor */
	public LocomotiveGroup(int id, String name) {
		this.id = id;
		this.name = name;
	}

	/** full constructor */
	public LocomotiveGroup(int id, String name,
			SortedSet<Locomotive> locomotives) {
		this.id = id;
		this.name = name;
		this.locomotives = locomotives;
	}

	// Property accessors

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		int old = this.id;
		this.id = id;
		//firePropertyChange(PROPERTYNAME_ID, old, id);
	}

	@Column(name = "name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		String old = this.name;
		this.name = name;
		firePropertyChange(PROPERTYNAME_NAME, old, name);
	}

	@Sort(type = SortType.NATURAL)
	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER, mappedBy = "locomotiveGroup")
	public SortedSet<Locomotive> getLocomotives() {
		return this.locomotives;
	}

	@Sort(type = SortType.NATURAL)
	public void setLocomotives(SortedSet<Locomotive> locomotives) {
		SortedSet<Locomotive> old = this.locomotives;
		this.locomotives = locomotives;
		//firePropertyChange(PROPERTYNAME_LOCOMOTIVES, old, locomotives);
	}

}
