#!/usr/bin/expect

set BUS 1
set ADDR 10

spawn telnet localhost 4303
expect "srcpd"
send "SET CONNECTIONMODE SRCP COMMAND\n"
expect "202 OK CONNECTIONMODE"
send "GO\n"
expect "200 OK GO"
send "INIT $BUS GA $ADDR M\n"
expect "200 OK"
send "TERM $BUS GA $ADDR\n"
expect "200 OK"
send "TERM 0 SESSION\n"
exit
