/*------------------------------------------------------------------------
 * 
 * copyright : (C) 2008 by Benjamin Mueller 
 * email     : news@fork.ch
 * website   : http://sourceforge.net/projects/adhocrailway
 * version   : $Id: LocomotiveGroup.java 199 2012-01-14 23:46:24Z fork_ch $
 * 
 *----------------------------------------------------------------------*/

/*------------------------------------------------------------------------
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 *----------------------------------------------------------------------*/

package ch.fork.AdHocRailway.services.impl.hibernate.locomotives;

// Generated 08-Aug-2007 18:10:44 by Hibernate Tools 3.2.0.beta8

import java.util.SortedSet;
import java.util.TreeSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Sort;
import org.hibernate.annotations.SortType;

import com.jgoodies.binding.beans.Model;

/**
 * LocomotiveGroup generated by hbm2java
 */
@Entity
@Table(name = "locomotive_group", uniqueConstraints = {})
public class HibernateLocomotiveGroup extends Model implements
		java.io.Serializable, Comparable<HibernateLocomotiveGroup> {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 4135734033419296582L;

	@Id
	@GeneratedValue
	private int id;

	private String name;

	@Sort(type = SortType.NATURAL)
	private SortedSet<HibernateLocomotive> locomotives = new TreeSet<HibernateLocomotive>();

	@Override
	public int compareTo(HibernateLocomotiveGroup o) {
		if (this == o) {
			return 0;
		}
		if (o == null) {
			return -1;
		}
		return name.compareTo(o.getName());
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final HibernateLocomotiveGroup other = (HibernateLocomotiveGroup) obj;
		if (id != other.id) {
			return false;
		}
		if (name == null) {
			if (other.name != null) {
				return false;
			}
		} else if (!name.equals(other.name)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return name;
	}

	// Constructors

	/** default constructor */
	public HibernateLocomotiveGroup() {
	}

	/** minimal constructor */
	public HibernateLocomotiveGroup(int id, String name) {
		this.id = id;
		this.name = name;
	}

	/** full constructor */
	public HibernateLocomotiveGroup(int id, String name,
			SortedSet<HibernateLocomotive> locomotives) {
		this.id = id;
		this.name = name;
		this.locomotives = locomotives;
	}

	// Property accessors

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = false, nullable = false, insertable = true, updatable = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Sort(type = SortType.NATURAL)
	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER, mappedBy = "locomotiveGroup")
	public SortedSet<HibernateLocomotive> getLocomotives() {

		if (locomotives == null) {
			locomotives = new TreeSet<HibernateLocomotive>();
		}
		return this.locomotives;
	}

	@Sort(type = SortType.NATURAL)
	public void setLocomotives(SortedSet<HibernateLocomotive> locomotives) {
		this.locomotives = locomotives;
	}

}
